Repository dayjack/SafeArea, pull requests merged in 2023-07, with the labels that each got.

#171 [Feat/#170] 맵마커 다중 선택 안되게 수정
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Feat

#173 [Design/#172] 상단바 기기별 대응
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
Labels: Design

#175 [Design/#174] 체크리스트뷰 스크롤뷰로 변경
  SafeArea/SafeArea/App/MainCheckListView.swift
Labels: Design

#177 [Design] - Onboarding Resizing
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/OnboardingView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
Labels: Design

#179 Sangyong design/#178
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4(2).imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4(2).imageset/onbo_4.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4(2).imageset/onbo_4@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4(2).imageset/onbo_4@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4.imageset/onbo_4.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4.imageset/onbo_4@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_4.imageset/onbo_4@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5(2).imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5(2).imageset/onbo_5.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5(2).imageset/onbo_5@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5(2).imageset/onbo_5@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5.imageset/onbo_5.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5.imageset/onbo_5@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_5.imageset/onbo_5@3x.png
Labels: Design

#182 [Feat] - 데이터 수집
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
Labels: Feat

#184 [chore/#183] 앱 아이콘 사각형 이미지로 변경, iOS 만 허용
  SafeArea/Pods/Target Support Files/Pods-SafeArea/Pods-SafeArea-frameworks.sh
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/92.png
Labels: Chore

#185 [Fix] - 오류 수정
  SafeArea/SafeArea/Global/View/MainMapTopView.swift
Labels: Fix

#187 [Feat/#186] 수집되는 데이터 컬럼 늘리기 위해 모델 수정 및 파라미터 추가
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
  SafeArea/SafeArea/Model/ChargingStationAnnotationModel.swift
Labels: Feat
