Repository dayjack/SafeArea, pull requests merged in 2023-06, with the labels that each got.

#2 [Setting/#1] 이슈, PR 템플릿 작성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Setting

#5 [Setting/#4] .gitignore 수정
  .gitignore
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SafeArea/SafeArea.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: Setting

#10 [Setting/#7] API 키 추가 세팅
  .gitignore
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/Extension/3.swift
  SafeArea/SafeArea/Global/Extension/BundleExtension.swift
Labels: Setting

#12 [Setting/#11] Secrets.plist 추가
  SafeArea/SafeArea.xcodeproj/project.pbxproj
Labels: Setting

#14 [Feat/#13] Api들 호출 테스트
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/Extension/BundleExtension.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Info.plist
  SafeArea/SafeArea/Model/ChargingStationModel.swift
  SafeArea/SafeArea/Model/Weather.swift
  SafeArea/SafeArea/Model/ZscodeData.swift
Labels: Feat

#16 CoreLocation 좌표
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Model/LocationViewModel.swift
  SafeArea/SafeArea/Resources/Secrets.plist
Labels: Feat

#20 [Design/#19] 하단 탭바 레이아웃 샘플 추가
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
  SafeArea/SafeArea/Global/View/RoundedCorner.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist.imageset/icon_checklist.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist.imageset/icon_checklist@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist.imageset/icon_checklist@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline.imageset/icon_guideline.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline.imageset/icon_guideline@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline.imageset/icon_guideline@3x.png
Labels: Design

#22 [Design/#21] 하단 탭바 선택 색상 적용 & 커스텀 색상 넣기
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/Extension/ColorExtension.swift
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_activated.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_activated.imageset/icon_checklist_activated.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_activated.imageset/icon_checklist_activated@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_activated.imageset/icon_checklist_activated@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_unactivated.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_unactivated.imageset/icon_checklist_unactivated.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_unactivated.imageset/icon_checklist_unactivated@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_checklist_unactivated.imageset/icon_checklist_unactivated@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_activated.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_activated.imageset/icon_guideline_activated.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_activated.imageset/icon_guideline_activated@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_activated.imageset/icon_guideline_activated@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_unactivated.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_unactivated.imageset/icon_guideline_unactivated.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_unactivated.imageset/icon_guideline_unactivated@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_guideline_unactivated.imageset/icon_guideline_unactivated@3x.png
Labels: Design

#27 [Setting/#23] Font 추가 & 세팅
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/SafeAreaApp.swift
  SafeArea/SafeArea/Global/Extension/FontExtension.swift
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
  SafeArea/SafeArea/Resources/Fonts/2.swift
  SafeArea/SafeArea/Resources/Fonts/Pretendard-Bold.ttf
  SafeArea/SafeArea/Resources/Fonts/Pretendard-Light.ttf
  SafeArea/SafeArea/Resources/Fonts/Pretendard-Medium.ttf
  SafeArea/SafeArea/Resources/Fonts/Pretendard-Regular.ttf
  SafeArea/SafeArea/Resources/Fonts/Pretendard-SemiBold.ttf
Labels: Setting

#30 [Design/#29] 메인 뷰 탭 구성 & 화면이동
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/App/MainGuideView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
Labels: Design

#32 [Feat/#31] MainMapView에 맵 구성요소 추가
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
Labels: Feat

#35 [Chore] - 날씨 온도 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
Labels: Chore

#37 [Design] - GuideLineView 생성
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainGuideView.swift
  SafeArea/SafeArea/Global/Extension/ColorExtension.swift
  SafeArea/SafeArea/Global/View/GuideDetailView_1.swift
  SafeArea/SafeArea/Global/View/GuideDetailView_2.swift
  SafeArea/SafeArea/Global/View/GuideDetailView_3.swift
  SafeArea/SafeArea/Global/View/GuidePageTabView.swift
  SafeArea/SafeArea/Global/View/GuideSelectButtonView.swift
Labels: Design

#38 [Design/#33] 체크리스트 뷰 레이아웃 작업
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/Modifier/5.swift
  SafeArea/SafeArea/Global/Modifier/CheckboxStyle.swift
  SafeArea/SafeArea/Global/Modifier/PretendardTextModifier.swift
  SafeArea/SafeArea/Global/View/4.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
  SafeArea/SafeArea/Model/WeekStore.swift
Labels: Design

#40 [Design/#39] Calendar 추가 & 색상 넣을 수 있게
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Design

#44 [Feat/#43] CheckList Sqlite 연동 기본 세팅
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/App/SafeAreaApp.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/Helper/DBHelper.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
  SafeArea/SafeArea/Model/CheckListModel.swift
Labels: Feat

#47 [Feat/#45] 날짜별 체크리스트 저장(처음 화면 로딩시 내일 날짜로 불러오는 버그)
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/Helper/DBHelper.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
  SafeArea/SafeArea/Model/WeekStore.swift
Labels: Feat

#50 [Design] - MainMapTopView 추가
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_1.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_2.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_3.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_4.swift
  SafeArea/SafeArea/Global/View/MainMapTopView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/Union.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/Union.imageset/Union.png
  SafeArea/SafeArea/Resources/Assets.xcassets/Union2.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/Union2.imageset/Union2.png
  SafeArea/SafeArea/Resources/Assets.xcassets/cloud+sun.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/cloud+sun.imageset/cloud+sun.png
  SafeArea/SafeArea/Resources/Assets.xcassets/cloud.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/cloud.imageset/cloud.png
  SafeArea/SafeArea/Resources/Assets.xcassets/cloudrain.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/cloudrain.imageset/Group 23.png
  SafeArea/SafeArea/Resources/Assets.xcassets/fog.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/fog.imageset/fog.png
  SafeArea/SafeArea/Resources/Assets.xcassets/hot.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/hot.imageset/hot.png
  SafeArea/SafeArea/Resources/Assets.xcassets/rain.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/rain.imageset/rain.png
  SafeArea/SafeArea/Resources/Assets.xcassets/snow.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/snow.imageset/snow.png
  SafeArea/SafeArea/Resources/Assets.xcassets/sun.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/sun.imageset/sun.png
  SafeArea/SafeArea/Resources/Assets.xcassets/thunder.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/thunder.imageset/thunder.png
  SafeArea/SafeArea/Resources/Assets.xcassets/weatherInfoImage.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/weatherInfoImage.imageset/weatherInfoImage.png
  SafeArea/SafeArea/Resources/Assets.xcassets/whiteRec.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/whiteRec.imageset/whiteRec.png
  SafeArea/SafeArea/Resources/Assets.xcassets/wind.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/wind.imageset/wind.png
Labels: Design

#51 [Feat/#48] 날짜별 체크리스트 개수 -> 색상 변경 연동
  SafeArea/SafeArea/Global/Extension/ColorExtension.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Feat

#53 [Feat] - Emergency Button 추가
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
  SafeArea/SafeArea/Global/View/MainMapTopView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/emergencyButton.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/emergencyButton.imageset/Group 2.png
  SafeArea/SafeArea/Resources/Assets.xcassets/emergencyButton.imageset/Group 2@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/emergencyButton.imageset/Group 2@3x.png
Labels: Feat

#55 [Design/#54] 체크리스트뷰 디자인 변경사항 적용 & 년/월 고정텍스트 클릭시 변경 & 선택날짜 회색 & 날짜뷰 버튼으로 변경
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Design

#57 [Design/#56] PlaceAnnotationView 추가
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/placeMarker.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/placeMarker.imageset/placeMarker.png
  SafeArea/SafeArea/Resources/Assets.xcassets/placeMarker.imageset/placeMarker@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/placeMarker.imageset/placeMarker@3x.png
Labels: Design

#61 [Design/#58] 현재 위치 버튼 추가 & 유저 위치 색상 변경
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Design

#63 [Design/#62] 체크리스트뷰 색상 잘못된 부분 변경
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Design

#65 [Chore/#64] 캘린더 첫 실행시 현재 주간 시작 날짜가 잘못된 버그 수정
  SafeArea/SafeArea/Model/WeekStore.swift
Labels: Chore

#67 [Feat] - 데이터 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Model/ChargingStationAnnotationModel.swift
Labels: Feat

#69 [Feat/#68] Map Annotation 데이터 변경
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/View/MainMapTopView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Feat

#71 [Design/#70] 홈 버튼 교체 + 애니메이션
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home@3x.png
Labels: Design

#73 [Feat] - CardView, MapAnnotationView 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/View/GuidePageTabView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/card1.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/card1.imageset/card1.png
  SafeArea/SafeArea/Resources/Assets.xcassets/card2.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/card2.imageset/card2.png
  SafeArea/SafeArea/Resources/Assets.xcassets/card3.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/card3.imageset/card3.png
Labels: Feat

#75 [Chore/#74] BottomTab 공백 뜨는 부분 수정
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
Labels: Chore

#79 [Feat/#78] swiftui-bottom-sheet-drawer 레이아웃만 만들기
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Feat

#81 [Chore/#80] 체크리스트 변경 시 색상 화면 리로드하지 않고 바뀌도록 수정
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Chore

#83 [Feat/#82] Gauge 퍼센트 계산 기능 추가
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Feat

#85 [Chore/#84] Gauge 계산 방식 기획대로 변경
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Chore

#87 [Fix/#86] 캘린더 시간대 버그 수정
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
  SafeArea/SafeArea/Model/WeekStore.swift
Labels: Fix

#89 [Fix/#88] 체크리스트 새로고침 없이 색상 변경 기능 삭제 -> 저장기능에 문제가 있었음
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Del

#91 [Feat/#90] Alert 수정 - 신고 시 빨간 색 배경
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
Labels: Feat

#94 [Fix/#93] Calendar 한주의 시작을 일요일로 변경 && 현재 날짜 표시 정상적으로 되도록 수정
  SafeArea/SafeArea/Model/WeekStore.swift
Labels: Fix

#96 [Fix/#95] Calendar 잔버그 한국시 관련 수정 -9 -> +9
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
Labels: Fix

#98 [Fix/#97] 체크리스트 과거 날짜는 변경 못하도록 수정
  SafeArea/SafeArea/App/MainCheckListView.swift
Labels: Fix

#100 [Fix/#99] Calendar 버그 수정 -> formatdate가 한국시간 적용을 못해 생기는 문제 해결(다른 함수 정의)
  SafeArea/SafeArea/App/MainCheckListView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Fix

#103 [Feat/#102] 충전소 거리 계산 기능 추가(차도기준)
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/MarkerInfoView.swift
  SafeArea/SafeArea/Model/LocationViewModel.swift
Labels: Feat

#105 [Design/#104] 홈 버튼 grayScale
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
Labels: Design

#107 [Design/#106] 홈 버튼 투명도 조정
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
Labels: Design

#109 [Design/#108] 충전 가능 텍스트 및 색 변경
  SafeArea/SafeArea/Global/View/MarkerInfoView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Design

#111 [Fix/#110] 날짜 색상 전체 화면 리로드 없이 변경되도록 & 체크박스 변경
  SafeArea/SafeArea/Global/Modifier/CheckboxStyle.swift
  SafeArea/SafeArea/Global/View/CustomWeekHeader.swift
Labels: Fix

#113 [Feat/#112] 데이터 거리 계산 & 정렬하여 리스트에 보여주기
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/Extension/ViewExtension.swift
  SafeArea/SafeArea/Global/View/MarkerInfoView.swift
  SafeArea/SafeArea/Model/ChargingStationAnnotationModel.swift
Labels: Feat

#117 [Feat] - 온보딩 뷰 만들기
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/View/OnboardingIndicator.swift
Labels: Feat

#119 [Feat/#116] 목록보기 버튼
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Feat

#121 [Chore/#120] 거리 리스트 밑에 Space 주기
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Chore

#125 [Fix/#124] 온보딩 뷰 버그 수정
  SafeArea/SafeArea/App/OnboardingView.swift
  SafeArea/SafeArea/Global/View/OnboardingIndicator.swift
Labels: Fix

#126 [Feat] - AppStorage, 파일정리
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/OnboardingView.swift
  SafeArea/SafeArea/Global/View/OnboardingIndicator.swift
  SafeArea/SafeArea/Global/View/OnboardingView_1.swift
  SafeArea/SafeArea/Global/View/OnboardingView_2.swift
  SafeArea/SafeArea/Global/View/OnboardingView_3.swift
Labels: Feat

#128 [Feat/#127] 데이터 합치기 개선
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
Labels: Feat

#130 [Feat/#129] 데이터 합치기 복구
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
Labels: Feat

#132 [Fix/#131] 데이터 정리 수정
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
Labels: Fix

#134 [Fix/#133] 충전소 정보 뷰 제대로 뜨도록 수정?
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Fix

#136 [Fix] - MapMarkerInfoView 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Fix

#138 [Chore] - 문자 메시지 수정
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
Labels: Chore

#140 [Feat/#139] API 충전소 개수 제한 해제
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Extension/ContentViewExtension.swift
  SafeArea/SafeArea/Global/Helper/RegionWrapper.swift
Labels: Feat

#144 [Fix/#141] 처음 보여주는 위치 현재 위치로 수정
  SafeArea/SafeArea/App/ContentView.swift
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/Helper/RegionWrapper.swift
Labels: Fix

#146 [Fix/#145] 리스트 차도 기준 거리 정렬
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Fix

#148 [Setting/#147] 다크모드 허용 x, 가로모드 허용 x
  .gitignore
  SafeArea/SafeArea.xcodeproj/project.pbxproj
Labels: Setting

#150 [Setting/#149] 프로젝트 세팅
  .gitignore
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Resources/Secrets.plist
Labels: Setting

#155 [Fix/#154] Map 화면 다시 열 때 줌 아웃 되어있던 현상 -> 줌 인
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/App/MapView.swift
  SafeArea/SafeArea/Global/Helper/RegionWrapper.swift
Labels: Fix

#157 [Fix/#156] 맵 화면 재입장 시 현재위치 버튼 작동하지 않는 현상 수정
  SafeArea/SafeArea/App/MainMapView.swift
Labels: Fix

#159 [Design] - 날씨에 대한 멘트 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_1.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_2.swift
  SafeArea/SafeArea/Global/View/MainMapTopDescriptionView_3.swift
Labels: Design

#161 [Design] - AppIcon변경, 홈아이콘 변경
  SafeArea/SafeArea/Global/View/CustomBottomTabView.swift
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  SafeArea/SafeArea/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/homeButton 3.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/icon_home.imageset/icon_home@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1@3x.png
Labels: Design

#163 [Feat] - SplashScreenView 생성
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/SafeAreaApp.swift
  SafeArea/SafeArea/App/SplashScreenView.swift
  SafeArea/SafeArea/Info.plist
  SafeArea/SafeArea/Resources/Assets.xcassets/launchIcon.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/launchIcon.imageset/launchIcon.png
  SafeArea/SafeArea/Resources/Assets.xcassets/launchIcon.imageset/launchIcon@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/launchIcon.imageset/launchIcon@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/launchscreen.imageset/Contents.json
  SafeArea/SafeArea/Resources/Assets.xcassets/launchscreen.imageset/launchscreen.png
  SafeArea/SafeArea/Resources/Assets.xcassets/launchscreen.imageset/launchscreen@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/launchscreen.imageset/launchscreen@3x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1@2x.png
  SafeArea/SafeArea/Resources/Assets.xcassets/onbo_1.imageset/onbo_1@3x.png
Labels: Feat

#165 [Design] - SplashScreenView 수정
  SafeArea/SafeArea/App/SplashScreenView.swift
Labels: Design

#167 [Fix/#166] 맵 처음 로드시 위도 경도 0,0 위치 불러오지 않도록 수정
  SafeArea/SafeArea.xcodeproj/project.pbxproj
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/App/MapView.swift
  SafeArea/SafeArea/Global/Helper/RegionWrapper.swift
Labels: Fix

#169 [Design] - 최종
  SafeArea/SafeArea/App/MainMapView.swift
  SafeArea/SafeArea/Global/View/EmergencyButtonView.swift
  SafeArea/SafeArea/Global/View/PlaceAnnotationView.swift
Labels: Design
